title:              Jekyll Foundation Starter

# Versioning
foundation_version: 6.2.1

author:
  name:             username
  email:            user@domain.com
  github:           username
  twitter:          username

# Dependencies
markdown:           kramdown
#Syntax Highlighter
#highlighter:        pygments

# Permalinks
permalink:          pretty

# Server
port:               4000
baseurl:            ""
url:                http://yoururl.com

# exclude this stuff when building the static site
exclude:            [
                      '.gitignore',
                      'README.md',
                      'Gemfile',
                      'Gemfile.lock',
                    ]

## CUSTOM VARS

#ga_id:             ##-########-###
site_name:          Jekyll Foundation Starter
site_description :  The awesomeness of Foundation 6... powered by Jekyll
site_copyright:     Copyright (c) 2016 @rasms
site_url:           http://yoururl.com
site_email:         site@domain.com



# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          ./assets/stylesheets
  style:            :compressed


gems: [jekyll-sitemap, jekyll-feed, jekyll-gist]
